In [1]:
import numpy as np

In [2]:
# list into array
data = [6, 7.5, 8, 0, 1]
arr = np.array(data)
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
# equal length list into muti dimensional array
data1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr1 = np.array(data1)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# shape, dimension and data type of array
print(f"The shape of array is {arr.shape} and dimension is {arr.ndim}. The data type is {arr.dtype}. ")
print(f"The shape of array is: {arr1.shape} and dimension is {arr1.ndim}. The data type is {arr1.dtype}.")

The shape of array is (5,) and dimension is 1. The data type is float64. 
The shape of array is: (2, 4) and dimension is 2. The data type is int64.


In [5]:
# zero array
arr_zero = np.zeros(10)
arr_zero_2d = np.zeros((3, 6))
print(f"""The shape of array is {arr_zero.shape} and dimension is {arr_zero.ndim}. 
The data type is {arr_zero.dtype}. The array is {arr_zero}""")
print(f"""\n The shape of array is {arr_zero_2d.shape} and dimension is {arr_zero_2d.ndim}. 
The data type is {arr_zero_2d.dtype}. The array is \n{arr_zero_2d}""")

arr_zeros_like = np.zeros_like(arr1)
print(f"""The shape of original array is {arr1.shape} same as that of new array {arr_zeros_like.shape}.""" )

The shape of array is (10,) and dimension is 1. 
The data type is float64. The array is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 The shape of array is (3, 6) and dimension is 2. 
The data type is float64. The array is 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
The shape of original array is (2, 4) same as that of new array (2, 4).


In [6]:
# It’s not safe to assume that np.empty will return an array of all zeros. In many cases it will return 
#uninitialized garbage values.

arr_empty = np.empty((2, 3, 2))
arr_empty
print(arr_empty)


a = [[1,2,3], [4,5,6]]
arr_empty_like = np.empty_like(a)
print(arr_empty_like)

[[[ 2.31584178e+077 -3.11107983e+231]
  [ 3.45845952e-323  0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+000]]

 [[ 0.00000000e+000  0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+000]]]
[[5764607523034234880 5764607523034234880 3420889007388491779]
 [3327992364838840684 3399705548884422446     853186666507822]]


In [7]:
# arange is an array-valued version of the built-in Python range function
arr_arange = np.arange(10)
arr_arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr_asarray = np.asarray([1, 2, 3])
arr_asarray

array([1, 2, 3])

In [9]:
# create ones array
arr_ones = np.ones(5)
arr_ones_2d = np.ones((5, 3))
print("1d array is: ", arr_ones)
print("2d array is: \n", arr_ones_2d)

1d array is:  [1. 1. 1. 1. 1.]
2d array is: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
a = np.asarray([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
arr_ones_like = np.ones_like(a)
print(f"The shape of original array \n {a} is \n {a.shape} and that of new array \n{arr_ones_like} is \n{arr_ones_like.shape}")

The shape of original array 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] is 
 (2, 5) and that of new array 
[[1 1 1 1 1]
 [1 1 1 1 1]] is 
(2, 5)


In [18]:
# return matrix with 0 and 1 values
arr_eye = np.eye(3, 3, k = 1)
print("The matrix with zero and one is: \n",arr_eye)
arr_identity = np.identity(3)
print("\n The identity matrix is: \n", arr_identity)

The matrix with zero and one is: 
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

 The identity matrix is: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
